//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shepherd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string ChurchId { get; set; }
        public System.DateTime DateBaptized { get; set; }
        public int BaptizedById { get; set; }
        public string MaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public string LandLine { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public int StatusId { get; set; }
        public int MemberTypeId { get; set; }
        public int ChurchDesignationId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
