//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shepherd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string ChurchId { get; set; }
        public string LocaleChurchId { get; set; }
        public System.DateTime DateBaptized { get; set; }
        public string Baptizer { get; set; }
        public byte MaritalStatusId { get; set; }
        public string SpouseName { get; set; }
        public string LandLine { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public byte MemberStatusId { get; set; }
        public byte DesignationId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual MemberStatus MemberStatu { get; set; }
        public virtual Person Person { get; set; }
    }
}
