//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shepherd.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShepherdContext : DbContext
    {
        public ShepherdContext()
            : base("name=ShepherdContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GatheringType> GatheringTypes { get; set; }
        public virtual DbSet<MemberStatus> MemberStatuses { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<DesignationType> DesignationTypes { get; set; }
        public virtual DbSet<GatheringSchedule> GatheringSchedules { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Committee> Committees { get; set; }
        public virtual DbSet<CommitteeMember> CommitteeMembers { get; set; }
    }
}
